on:
  push

jobs:
  lint: 
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - run: yarn install --frozen-lockfile

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      
      - run: yarn install --frozen-lockfile
      - run: yarn build

      - uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST_ADDRESS }}
          username: ${{ secrets.HOST_USER }}
          password: ${{ secrets.HOST_PASSWORD }}
          port: ${{ secrets.HOST_PORT }}
          overwrite: true
          strip_components: 1
          source: dist/*
          target: /var/www/static/market-otus/
